config/routes.rb
Changed the routes from :rented_tablescapes to :tablescapes
=> changed routes

Gemfile, Gemfile.lock, db/seeds.rb
Seeds are now working properly. Will need to "yarn" and "bundle". May also need to "brew install heroku/brew/heroku"
=> Got seeds working properly.

app/controllers/tablescapes_controller.rb, app/views/pages/home.html.erb, app/views/tablescapes/index.html.erb, app/views/tablescapes/search_results.html.erb, config/routes.rb, db/seeds.rb
Branch which includes the search form on the home page with another link to get the full index, new route to a search_results page (inside tablescapes views) to display search results, and an index page for displaying all tablescapes.
=> Pushing home_page_and_index_tablescapes to GitHub

app/assets/stylesheets/components/_card.scss, app/views/tablescapes/search_results.html.erb
Phil's new and shiny search results page
=> embedded ruby code added to search results page

app/assets/stylesheets/pages/_show.scss, app/controllers/tablescapes_controller.rb, app/views/tablescapes/show.html.erb
=> improved show page

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_home-card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
Please review the tidies to the home-page, now reformatted and certain files added for the styling to the home page.
=> Tidying home page finished

app/assets/stylesheets/components/_form-home.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_show.scss, app/views/pages/home.html.erb
Fixed the scss files for forms on the home page and show page. Please review and merge.
=> Fixed scss for forms on home page and show page

app/assets/stylesheets/pages/_show.scss, app/views/layouts/application.html.erb
very small fix. show form and navbar link
=> fixed show form and navbar link

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_search-card.scss, app/views/tablescapes/index.html.erb
=> Index page changes phil

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_search-card.scss
Changes to search page and responsive formatting done.
Please check and merge
=> formatting done for search

app/views/layouts/application.html.erb
=> added log out

Gemfile, app/models/tablescape.rb, config/application.rb, db/migrate/20191120131345_add_image_to_tablescapes.rb, db/schema.rb, db/seeds.rb
=> Added image urls to the tablescapes model.

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_search-card.scss, app/views/tablescapes/index.html.erb, app/views/tablescapes/search_results.html.erb
Finalised version of search and index page
=> finalised index and search page

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/stylesheets/application.scss, app/controllers/bookings_controller.rb, app/views/bookings/show.html.erb, app/views/layouts/application.html.erb, app/views/tablescapes/show.html.erb, config/routes.rb
=> added new booking confirmation page and change routes a little

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_form-home.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_flashes.html.erb
Fixed the flashes to remove the empty space on homepage, amended centring of text on home page, added tagline, added fourth card for home page. Please review and merge.
=> Fixed flashes and tweaked homepage to amend title

app/models/tablescape.rb, app/views/layouts/application.html.erb, app/views/tablescapes/index.html.erb, config/environments/development.rb, config/storage.yml, db/migrate/20191121104947_create_active_storage_tables.active_storage.rb, db/schema.rb
Added cloudinary gem and configurations
=> added cloudinary config

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb
Added the image to the fourth card and also set the home page cards to wrap to be responsive.
=> Added fourth card to home page and set to wrap

app/assets/stylesheets/components/_banner.scss, app/javascript/components/banner.js, app/javascript/packs/application.js, app/views/pages/home.html.erb, package.json, yarn.lock
Added typed.js to the banner tagline on the home page and fixed some home page formatting (letter spacing for the h1)
Need to yarn install for the new typed.js npm.
=> Added typed.js to home page as well as altering home page h1 style

app/controllers/tablescapes_controller.rb, app/views/tablescapes/index.html.erb, app/views/tablescapes/new.html.erb
Working on routes and controller for adding new table set
=> started on routes and controller for adding and creating new tablescape

Gemfile, Gemfile.lock, app/controllers/tablescapes_controller.rb, app/models/tablescape.rb
Updated the search form on home page to use pg search gem to search only on :tag, including updating tablescapes controller method.
Please review and merge. Remember to bundle install for new gem!
=> Added the pg search gem

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_form-edit.scss, app/assets/stylesheets/components/_form-new.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/tablescapes_controller.rb, app/models/tablescape.rb, app/views/tablescapes/edit.html.erb, app/views/tablescapes/index.html.erb, app/views/tablescapes/new.html.erb, app/views/tablescapes/show.html.erb
forms done for new and edit. These will need adjusting to add items field. Was not able to work this
=> forms for new and edit done

app/assets/stylesheets/components/_card-bookings-index.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_bookings-index.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_show.scss, app/controllers/bookings_controller.rb, app/controllers/reviews_controller.rb, app/controllers/tablescapes_controller.rb, app/models/booking.rb, app/models/review.rb, app/models/tablescape.rb, app/views/bookings/index.html.erb, app/views/layouts/application.html.erb, app/views/tablescapes/show.html.erb, config/routes.rb, db/migrate/20191121134839_create_reviews.rb, db/schema.rb, test/controllers/reviews_controller_test.rb, test/models/review_test.rb
Added feature to see your bookings (through link in navbar) when logged in. Reviews will also be shown for tablescapes at the bottom of their show page.
Please review, there may be conflicts.
=> Added half of the reviews feature

.gitignore, app/assets/stylesheets/pages/_devise-new.scss, app/assets/stylesheets/pages/_index.scss, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb
Just a little update to the devise sign-in page to make it look nicer.
=> Devise sign-in page update

app/views/tablescapes/index.html.erb, app/views/tablescapes/search_results.html.erb
Fixed bug for the photos appearing on the search and removed erroneous leftover buttons.
=> Fixed bug and removed leftover unnecessary buttons

app/assets/javascripts/application.js, app/javascript/components/banner.js, app/javascript/packs/application.js, app/views/tablescapes/index.html.erb, app/views/tablescapes/search_results.html.erb, app/views/tablescapes/show.html.erb
carousels added to index, search_page and show-page
=> Carousel final

app/assets/stylesheets/components/_card-bookings-index.scss, app/controllers/bookings_controller.rb, app/controllers/reviews_controller.rb, app/models/review.rb, app/views/bookings/index.html.erb, app/views/tablescapes/show.html.erb, config/routes.rb
Bookings index page finished to include links to create (with modal), delete reviews.
=> Finishing of Bookings index page

app/views/tablescapes/show.html.erb
Minor change to reverse the order of reviews on the tablescape page. Please review and merge.
=> Reversed order of reviews on tablescape show page

app/assets/stylesheets/components/_index.scss, app/views/bookings/index.html.erb
Fixed the bugs from latest master.
=> Fixed bugs from previous merge

app/assets/stylesheets/components/_form-home.scss, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
Tweaked navbar to separate sections, updated homepage form buttons to change sizing to be more even.
=> Tweaked navbar appearance and minor changes to form on home page

app/assets/config/manifest.js, config/initializers/content_security_policy.rb, config/webpack/environment.js, db/resources/items.txt, db/seeds.rb
=> More realistic items.

app/assets/stylesheets/components/_card-bookings-index.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_form-home.scss, app/assets/stylesheets/components/_home-card.scss, app/assets/stylesheets/components/_search-card.scss, app/assets/stylesheets/pages/_bookings-index.scss, app/assets/stylesheets/pages/_bookings-show.scss, app/assets/stylesheets/pages/_show.scss
Fiexd the fonts to remove remaining references to Alveria font and instead replace it with Roboto.
=> Fixed fonts to be consistent throughout

app/assets/stylesheets/pages/_bookings-index.scss
Centralised the h2 on the bookings index page.
=> Fixed centralising h2 text on bookings index

app/controllers/tablescapes_controller.rb, app/views/tablescapes/edit.html.erb, app/views/tablescapes/new.html.erb, app/views/tablescapes/show.html.erb
Now only authors can edit their tablescape.
=> Now only authors can edit their tablescape.

app/assets/stylesheets/pages/_bookings-show.scss
Fixed CSS on booking show page.
=> Fixed CSS on Booking show page

app/assets/stylesheets/components/_form-edit.scss, app/assets/stylesheets/components/_form-new.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_home.scss, app/views/shared/_navbar.html.erb, app/views/tablescapes/edit.html.erb, app/views/tablescapes/index.html.erb, app/views/tablescapes/new.html.erb, app/views/tablescapes/search_results.html.erb, app/views/tablescapes/show.html.erb
=> updates to forms

db/seeds.rb
Added first_name and last_name for Melissa in the seed file to get the personalised greeting in the navbar.
=> Update to seed to add first name last name for Melissa

app/assets/stylesheets/components/_card.scss, app/views/tablescapes/index.html.erb
Fixed the html of the index and colours of the buttons.
=> Fixing index bug

app/assets/stylesheets/pages/_show.scss, app/controllers/tablescapes_controller.rb, app/views/shared/_map.html.erb, app/views/tablescapes/show.html.erb
=> added map to showpage
